#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Independent packer for open.mp c6759bd8 Shared/NetCode/core.hpp PlayerInit::write.
# Uses Python struct + explicit MSB-first bit placement, not RakNet's encoder.
import struct
from pathlib import Path
bits=[]
def bit(value): bits.append(int(bool(value)))
def scalar(fmt,value):
 for byte in struct.pack('<'+fmt,value):bits.extend((byte>>shift)&1 for shift in range(7,-1,-1))
for value in [False,True,False,False]:bit(value)
scalar('f',200.0);bit(False);scalar('f',70.0)
for value in [True,False,False]:bit(value)
scalar('I',1);assert len(bits)==104
scalar('H',37);bit(True);scalar('I',1);scalar('B',12);scalar('B',10);scalar('f',0.008);bit(True);scalar('I',0);bit(False)
assert len(bits)==235
for value in [30,40,50,1,1]:scalar('I',value)
name=b'Fixture';scalar('B',len(name))
for byte in name:scalar('B',byte)
for _ in range(212):scalar('B',0)
scalar('I',0)
bit_count=len(bits)
while len(bits)%8:bit(False)
raw=bytes(sum(bits[i+j]<<(7-j) for j in range(8)) for i in range(0,len(bits),8))
text='// SPDX-License-Identifier: GPL-3.0-or-later\n// Generated by fixtures/make-init.py; pinned server-schema fixture.\n'
text+=f'static constexpr unsigned initFixtureBits={bit_count};\nstatic const unsigned char initFixture[]={{\n'
for i in range(0,len(raw),16):text+=' '+','.join(f'0x{x:02x}' for x in raw[i:i+16])+',\n'
text+='};\n'
Path(__file__).with_name('init.hpp').write_text(text)
