# SPDX-License-Identifier: GPL-3.0-or-later
"""Save exact decoded packed terrain as editable native source; never render.

Blender --background --factory-startup --python-exit-code 1 --python
  tools/assets/horizon-save.py -- --output-root SCRATCH --blender-version 5.2.1
Consumes assets/horizon-relief.json, assets/source/horizon-decoded.json and
horizon-build-pending.json from SCRATCH, all generated by horizon-bake.mjs.
The float32 LE sidecar avoids Python/JS trigonometric reconstruction differences.
"""
import argparse, base64, hashlib, json, pathlib, struct, sys
import bpy

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--output-root', required=True, type=pathlib.Path)
parser.add_argument('--blender-version', required=True, choices=['4.5.13', '5.2.1'])
args = parser.parse_args(sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else [])
root = args.output_root.resolve()
source = root / 'assets/source'
sha = lambda data: hashlib.sha256(data).hexdigest()
assert '.'.join(map(str, bpy.app.version)) == args.blender_version, 'Unexpected Blender version'
record = json.loads((source / 'horizon-build-pending.json').read_text())
sculpt_bytes = (root / 'assets/horizon-relief.json').read_bytes()
sculpt = json.loads(sculpt_bytes)
decoded = json.loads((source / 'horizon-decoded.json').read_text())
assert decoded['version'] == 1 and decoded['ground'] == 9
assert decoded['runtimeSha256'] == record['runtime']['sha256'] == sha(sculpt_bytes)
assert sha(pathlib.Path(__file__).read_bytes()) == record['inputs']['saveRecipe']['sha256']
assert sculpt['version'] == 4 and len(decoded['layers']) == 3
count = (sculpt['segments'] + 1) * (sculpt['rings'] + 1)
index_count = sculpt['segments'] * sculpt['rings'] * 6
formats = {'position': ('f', count*3), 'uv': ('f', count*2), 'index': ('H', index_count),
           'irradiance': ('B', count*3), 'geology': ('B', count*2)}
values = []
for number, layer in enumerate(decoded['layers']):
    fields = {}
    for key, (kind, length) in formats.items():
        raw = base64.b64decode(layer[key], validate=True)
        assert len(raw) == struct.calcsize('<' + str(length) + kind)
        expected = record['geometry'][number]['fields'][key]
        assert expected == {'bytes': len(raw), 'sha256': sha(raw)}, key
        fields[key] = struct.unpack('<' + str(length) + kind, raw)
    for k, elevation in enumerate(struct.unpack('<' + str(count) + 'h', base64.b64decode(sculpt['layers'][number]['elevation']))):
        assert fields['position'][k*3+2] == struct.unpack('<f', struct.pack('<f', 9 + elevation/256))[0]
    assert tuple(base64.b64decode(sculpt['layers'][number]['irradiance'])) == fields['irradiance']
    assert tuple(base64.b64decode(sculpt['layers'][number]['geology'])) == fields['geology']
    values.append(fields)

bpy.context.preferences.filepaths.save_version = 0
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
verified = []
for number, fields in enumerate(values):
    mesh = bpy.data.meshes.new('Arroyo packed ridge ' + str(number))
    vertices = [fields['position'][i:i+3] for i in range(0, count*3, 3)]
    faces = [fields['index'][i:i+3] for i in range(0, index_count, 3)]
    mesh.from_pydata(vertices, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(mesh.name, mesh)
    bpy.context.collection.objects.link(obj)
    obj['runtimeSourceSha256'] = sha(sculpt_bytes)
    obj['groundZ'] = 9
    obj['materialRecipe'] = 'apps/browser/src/horizon.ts; original grass and concrete maps; no live relighting'
    obj['irradianceScale'] = 4
    obj['sourcePurpose'] = 'Exact runtime geometry and editable field attributes; material preview shows irradiance only.'
    irradiance = mesh.color_attributes.new(name='Irradiance', type='FLOAT_COLOR', domain='POINT')
    geology = mesh.attributes.new(name='Geology', type='FLOAT2', domain='POINT')
    # Preserve vertex UVs in a point field as well as Blender loop UVs; neither
    # geometry nor UVs are reconstructed from Python trigonometry.
    vertex_uv = mesh.attributes.new(name='Runtime UV', type='FLOAT2', domain='POINT')
    uv = mesh.uv_layers.new(name='UVMap')
    # Attribute creation may relocate Blender CustomData; reacquire handles.
    irradiance = mesh.color_attributes['Irradiance']
    geology = mesh.attributes['Geology']
    vertex_uv = mesh.attributes['Runtime UV']
    for i in range(count):
        irradiance.data[i].color = tuple(x/255 for x in fields['irradiance'][i*3:i*3+3]) + (1,)
        geology.data[i].vector = tuple(x/255 for x in fields['geology'][i*2:i*2+2])
        vertex_uv.data[i].vector = fields['uv'][i*2:i*2+2]
    for loop in mesh.loops:
        uv.data[loop.index].uv = fields['uv'][loop.vertex_index*2:loop.vertex_index*2+2]
    material = bpy.data.materials.new('Irradiance inspection ' + str(number))
    material.use_nodes = True
    nodes, links = material.node_tree.nodes, material.node_tree.links
    nodes.clear()
    output, emission, attribute = nodes.new('ShaderNodeOutputMaterial'), nodes.new('ShaderNodeEmission'), nodes.new('ShaderNodeAttribute')
    attribute.attribute_name = 'Irradiance'
    emission.inputs['Strength'].default_value = 4
    links.new(attribute.outputs['Color'], emission.inputs['Color'])
    links.new(emission.outputs['Emission'], output.inputs['Surface'])
    mesh.materials.append(material)
    actual = {
        'position': tuple(c for vertex in mesh.vertices for c in vertex.co),
        'index': tuple(i for polygon in mesh.polygons for i in polygon.vertices),
        'uv': tuple(c for v in vertex_uv.data for c in v.vector),
        'irradiance': tuple(round(c*255) for v in irradiance.data for c in v.color[:3]),
        'geology': tuple(round(c*255) for v in geology.data for c in v.vector),
    }
    hashes = {}
    for key, (kind, length) in formats.items():
        assert actual[key] == fields[key], 'Native geometry/field differs: ' + key
        raw = struct.pack('<' + str(length) + kind, *actual[key])
        hashes[key] = {'bytes': len(raw), 'sha256': sha(raw)}
    verified.append({'vertices': len(mesh.vertices), 'triangles': len(mesh.polygons), 'fields': hashes})

bpy.context.scene['sourcePurpose'] = 'Exact decoded packed runtime terrain, not a rendered screenshot'
bpy.ops.wm.save_as_mainfile(filepath=str(source / 'horizon.blend'), compress=True)
metadata = {
    'runtimeSha256': sha(sculpt_bytes),
    'sourceSha256': sha((source / 'horizon.blend').read_bytes()),
    'saveRecipeSha256': sha(pathlib.Path(__file__).read_bytes()),
    'geometry': verified,
    'blender': {'version': args.blender_version, 'buildHash': bpy.app.build_hash.decode(),
                'executableSha256': sha(pathlib.Path(bpy.app.binary_path).read_bytes())},
}
(source / 'horizon-native.json').write_text(json.dumps(metadata, indent=2) + '\n')
print('HORIZON_NATIVE_SOURCE', json.dumps({'sha256': metadata['sourceSha256'], 'triangles': sum(x['triangles'] for x in verified)}))
