// SPDX-License-Identifier: GPL-3.0-or-later
#define main worker_entry
#include "worker.cpp"
#undef main
#include <ReliabilityLayer.h>
#include <stdexcept>
#include "fixtures/init.hpp"
#include <limits>
void check(bool ok,const char*message){if(!ok)throw std::runtime_error(message);}
std::string capture(std::function<void()>f){std::ostringstream out;auto*old=std::cout.rdbuf(out.rdbuf());f();std::cout.rdbuf(old);return out.str();}
void feed(ReliabilityLayer&layer,unsigned part,unsigned count,const std::string&data,unsigned message,unsigned bitLength=0,unsigned splitId=7,PacketReliability mode=RELIABLE){
 BitStream b;b.Write(false);b.Write(uint16_t(message));uint8_t reliability=mode;b.WriteBits(&reliability,4);if(mode==RELIABLE_ORDERED||mode==RELIABLE_SEQUENCED||mode==UNRELIABLE_SEQUENCED){uint8_t channel=0;b.WriteBits(&channel,5);b.Write(uint16_t(0));}b.Write(true);b.Write(uint16_t(splitId));b.WriteCompressed(uint32_t(part));b.WriteCompressed(uint32_t(count));b.WriteCompressed(uint16_t(bitLength?bitLength:data.size()*8));b.WriteAlignedBytes((const uint8_t*)data.data(),data.size());
 // Mirror RakPeer configuration: the standalone layer leaves progress notifications uninitialized.
 layer.SetSplitMessageProgressInterval(0);layer.SetUnreliableTimeout(0);
 DataStructures::List<PluginInterface*> plugins;bool ban=false;layer.HandleSocketReceiveFromConnectedPlayer((char*)b.GetData(),b.GetNumberOfBytesUsed(),{0x0100007f,7777},plugins,576,ban);
}
int main(int argc,char**argv){try{
 bool corrupt=argc>1&&std::string(argv[1])=="--corrupt-fixture";
 {uint8_t bytes[]={0x01,0x34,0x12};Reader r(bytes,sizeof(bytes));check(r.get<uint8_t>()==1&&r.get<uint16_t>()==(corrupt?0xffff:0x1234),"little endian fixture");bool threw=false;try{r.get<float>();}catch(...){threw=true;}check(threw,"truncated read rejected");}
 {uint8_t bytes[]={0xff};Reader r(bytes,1);bool threw=false;try{r.str8();}catch(...){threw=true;}check(threw,"invalid string length rejected");}
 {BitStream b;b.Write(float(0.000001));Reader r(b.GetData(),b.GetNumberOfBytesUsed());check(r.velocity()==Vec{0,0,0},"compressed velocity epsilon follows server");}
 {BitStream b;b.Write(uint8_t(207));b.Write(uint16_t(42));b.Write(false);b.Write(false);b.Write(uint16_t(8));writeVec(b,{12,-3,10});b.WriteNormQuat(1.f,0.f,0.f,0.f);b.Write(uint8_t(0xf0));b.Write(uint8_t(0));b.Write(uint8_t(0));b.Write(0.f);b.Write(false);b.Write(false);Packet p{};p.data=b.GetData();p.length=b.GetNumberOfBytesUsed();p.bitSize=b.GetNumberOfBitsUsed();auto e=json::parse(capture([&]{onSync(&p);}));check(e["id"]==42&&e["position"]==json({12,-3,10})&&e["mode"]=="onFoot"&&e["keys"]==8,"server direction compressed onFoot fixture preserves keys");}
 {BitStream b;b.Write(uint8_t(211));b.Write(uint16_t(42));b.Write(uint16_t(1));b.Write(uint16_t(0xc1));b.Write(uint8_t(100));b.Write(uint8_t(0));b.Write(uint16_t(0));b.Write(uint16_t(0));b.Write(uint16_t(2));writeVec(b,{0,6,10});Packet p{};p.data=b.GetData();p.length=b.GetNumberOfBytesUsed();p.bitSize=b.GetNumberOfBitsUsed();auto e=json::parse(capture([&]{onSync(&p);}));check(e["seat"]==1&&e["position"]==json({0,6,10})&&e["keys"]==2,"server passenger fixture has raw health bytes and key bits");}
 {ReliabilityLayer layer;feed(layer,1,2,"world",0);uint8_t*out=nullptr;check(layer.Receive(&out)==0,"partial fragment hidden");feed(layer,0,2,"hello",1);int bits=layer.Receive(&out);check(bits==80&&std::string((char*)out,bits/8)=="helloworld","reordered fragment assembly");delete[]out;}
 for(unsigned count:{0u,257u}){ReliabilityLayer layer;feed(layer,0,count,"invalid",0);uint8_t*out=nullptr;check(layer.Receive(&out)==0,"fragment count bounded");}
 {ReliabilityLayer layer;feed(layer,2,2,"invalid",0);uint8_t*out=nullptr;check(layer.Receive(&out)==0,"fragment index bounded");}
 {ReliabilityLayer layer;feed(layer,0,2,"hello",0);feed(layer,0,2,"evil!",1);feed(layer,1,2,"world",2);uint8_t*out=nullptr;int bits=layer.Receive(&out);check(bits==80&&std::string((char*)out,bits/8)=="helloworld","duplicate fragment index ignored");delete[]out;}
 {auto before=state;auto error=capture([]{input(R"({"type":"state","position":[1,2,"bad"],"rotation":[1,0,0,0],"velocity":[0,0,0]})");});check(json::parse(error)["type"]=="error"&&state==before,"invalid JSON state rejected atomically");}
 {controlRevision=7;auto before=state;json j=state;j["type"]="state";j["position"]={9,9,10};j["controlRevision"]=6u;capture([&]{input(j.dump());});check(state==before,"stale position revision ignored");j["controlRevision"]=7u;capture([&]{input(j.dump());});check(state["position"]==json({9,9,10}),"current revision accepted");before=state;j["mode"]="driver";j["vehicleId"]=1;j["seat"]=0;capture([&]{input(j.dump());});check(state==before,"browser cannot allocate its own seat");}
 {uint8_t data[]={0};RPCParameters p{};p.input=data;p.numberOfBitsOfData=8;auto out=json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(139));}));check(out["type"]=="error"&&!running,"truncated init fails connection explicitly");running=true;}
 {uint8_t bytes[1]={0};bool threw=false;try{Reader r(bytes,1,16);}catch(...){threw=true;}check(threw,"reader cannot expand beyond backing storage");}
 {BitStream b;b.Write(std::numeric_limits<float>::quiet_NaN());Reader r(b.GetData(),b.GetNumberOfBytesUsed());bool threw=false;try{r.get<float>();}catch(...){threw=true;}check(threw,"nonfinite heading rejected");}
 {BitStream b;b.WriteNormQuat(0.f,1.f,1.f,1.f);Reader r(b.GetData(),b.GetNumberOfBytesUsed());bool threw=false;try{r.quat();}catch(...){threw=true;}check(threw,"nonunit compressed quaternion rejected");}
 {auto before=state;json j=state;j["type"]="state";j["keys"]=1.5;j["controlRevision"]=controlRevision;auto error=json::parse(capture([&]{input(j.dump());}));check(error["type"]=="error"&&state==before,"fractional indexes rejected");}
 {BitStream b;b.Write(uint8_t(207));b.Write(uint16_t(42));b.Write(false);b.Write(false);b.Write(uint16_t(0));writeVec(b,{0,0,10});b.WriteNormQuat(1.f,0.f,0.f,0.f);b.Write(uint8_t(0xf0));b.Write(uint8_t(0));b.Write(uint8_t(0));b.Write(0.f);Packet p{};p.data=b.GetData();p.length=b.GetNumberOfBytesUsed();p.bitSize=b.GetNumberOfBitsUsed();check(capture([&]{onSync(&p);}).empty(),"missing onFoot trailing flags cannot publish state");}
 {BitStream b;b.Write(uint8_t(200));b.Write(uint16_t(42));b.Write(uint16_t(1));b.Write(uint16_t(0));b.Write(uint16_t(0));b.Write(uint16_t(2));b.WriteNormQuat(1.f,0.f,0.f,0.f);writeVec(b,{0,6,10});b.Write(0.f);Packet p{};p.data=b.GetData();p.length=b.GetNumberOfBytesUsed();p.bitSize=b.GetNumberOfBitsUsed();check(capture([&]{onSync(&p);}).empty(),"missing driver tail cannot publish state");b.Write(uint16_t(1000));b.Write(uint8_t(0xf0));b.Write(uint8_t(0));for(int i=0;i<4;i++)b.Write(false);p.length=b.GetNumberOfBytesUsed();p.bitSize=b.GetNumberOfBitsUsed();auto out=capture([&]{onSync(&p);});auto e=json::parse(out.substr(0,out.find('\n')));check(e["mode"]=="driver"&&e["seat"]==0&&e["keys"]==2,"complete driver fixture preserves horn key");}
 {ReliabilityLayer layer;std::string data((char*)initFixture,sizeof(initFixture));auto cut=data.size()/2;feed(layer,1,2,data.substr(cut),0,0,7,RELIABLE_ORDERED);feed(layer,0,2,data.substr(0,cut),1,0,7,RELIABLE_ORDERED);uint8_t*out=nullptr;int bits=layer.Receive(&out);check(bits==sizeof(initFixture)*8,"fragmented init fully reassembled");RPCParameters p{};p.input=out;p.numberOfBitsOfData=initFixtureBits;auto event=json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(139));}));check(event["type"]=="init"&&event["playerId"]==37&&event["onFootRate"]==30&&event["inCarRate"]==40,"independent fragmented init schema decoded");p.numberOfBitsOfData=299;auto error=json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(139));}));check(error["type"]=="error"&&!running,"init missing model table rejected");running=true;delete[]out;}
 {auto before=state;json j=state;j["type"]="state";j["position"]={1,2,3,4};j["controlRevision"]=controlRevision;auto error=json::parse(capture([&]{input(j.dump());}));check(error["type"]=="error"&&state==before,"oversized vectors rejected");}
 {auto before=state;json j=state;j["type"]="state";j["rotation"]={1.1,0,0,0};j["controlRevision"]=controlRevision;auto error=json::parse(capture([&]{input(j.dump());}));check(error["type"]=="error"&&state==before,"nonunit input quaternion rejected");}
 {ReliabilityLayer layer;feed(layer,0,2,"A",0,1);feed(layer,1,2,"B",1,1);uint8_t*out=nullptr;check(layer.Receive(&out)==0,"non-byte-aligned nonfinal fragment rejected before allocation/assembly");feed(layer,0,2,"A",2,8);int bits=layer.Receive(&out);check(bits==9&&out[0]=='A'&&out[1]=='B',"byte-aligned first fragment plus partial last safely assembles");delete[]out;}
 {ReliabilityLayer layer;feed(layer,0,2,"hello",0);feed(layer,1,3,"wrong",1);feed(layer,1,2,"world",2);uint8_t*out=nullptr;int bits=layer.Receive(&out);check(bits==80&&std::string((char*)out,10)=="helloworld","mismatched count rejected without reading freed packet");delete[]out;}
 {ReliabilityLayer layer;for(unsigned id=0;id<17;id++)feed(layer,0,2,"A",id,8,id);feed(layer,1,2,"B",17,8,16);uint8_t*out=nullptr;check(layer.Receive(&out)==0,"seventeenth channel rejected without reading freed packet");feed(layer,1,2,"B",18,8,0);check(layer.Receive(&out)==16,"existing channel can finish at capacity");delete[]out;}
 {ReliabilityLayer layer;feed(layer,0,2,"hello",0,0,7,RELIABLE_SEQUENCED);feed(layer,0,2,"evil!",1,0,7,RELIABLE_SEQUENCED);feed(layer,1,2,"world",2,0,7,RELIABLE_SEQUENCED);uint8_t*out=nullptr;int bits=layer.Receive(&out);check(bits==80&&std::string((char*)out,10)=="helloworld","sequenced duplicate rejection retains valid ownership");delete[]out;}
 // Independently source-derived SetRaceCheckpoint payload: uint8 type,
 // two raw little-endian float vectors, radius; unlike sync packets no compression.
 {uint8_t bytes[]={0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x40,0x41,0x00,0x00,0x20,0x41,0x00,0x00,0xf0,0x41,0x00,0x00,0x40,0x41,0x00,0x00,0x20,0x41,0x00,0x00,0x90,0x40};RPCParameters p{};p.input=bytes;p.numberOfBitsOfData=232;auto event=json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(38));}));check(event["type"]=="raceCheckpoint"&&event["position"]==json({0,12,10})&&event["nextPosition"]==json({30,12,10})&&event["radius"]==4.5,"independent server race checkpoint layout");for(unsigned bits:{0u,8u,231u}){p.numberOfBitsOfData=bits;check(json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(38));}))["type"]=="error","truncated checkpoint cannot publish marker");}p.numberOfBitsOfData=232;bytes[0]=9;check(json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(38));}))["type"]=="error","unknown checkpoint type rejected");bytes[0]=0;bytes[25]=0;bytes[26]=0;bytes[27]=0xc0;bytes[28]=0x7f;check(json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(38));}))["type"]=="error","nonfinite checkpoint radius rejected");}
 {RPCParameters p{};p.numberOfBitsOfData=0;auto event=json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(39));}));check(event["type"]=="raceCheckpointClear","zero-length race checkpoint disable");uint8_t byte=0;p.input=&byte;p.numberOfBitsOfData=8;check(json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(39));}))["type"]=="error","overlong checkpoint disable rejected");}
 {auto event=json::parse(capture([]{check(challengeNotice("ARROYO_RACE_V1 7 2 0 1 1 3 9 12500 0 41999 20000 0"),"challenge recognized");}));check(event["type"]=="challenge"&&event["generation"]==7&&event["phase"]=="running"&&event["checkpointIndex"]==3&&event["elapsedMs"]==12500&&event["reason"]=="none","versioned challenge state decoded");}
 for(const auto*bad:{"ARROYO_RACE_V1 7 2 0 1 1 3 9 12500 0 41999 20000", "ARROYO_RACE_V1 7 2 0 1 1 3 9 12500 0 41999 20000 0 extra", "ARROYO_RACE_V1 7 3 0 1 1 3 9 12500 0 41999 20000 0", "ARROYO_RACE_V1 7 2 0 1 1 9 9 12500 0 41999 20000 0", "ARROYO_RACE_V1 7 2 65535 1 1 3 9 12500 0 41999 20000 0", "ARROYO_RACE_V1 7 2 0 1 1 3 9 nan 0 41999 20000 0", "ARROYO_RACE_V1 7 2 0 1 1 3 9 1.5 0 41999 20000 0", "ARROYO_RACE_V1 7 2 0 1 1 3 9 999999999999999999999999 0 41999 20000 0", "ARROYO_RACE_V1 7 2 0 1 1 3 9 12500 3000 41999 20000 0"}){bool threw=false;try{challengeNotice(bad);}catch(...){threw=true;}check(threw,"malformed or inconsistent challenge state rejected");}
 for(const auto*bad:{"ARROYO_RACE_V1 0 2 0 1 1 0 9 1000 0 0 1000 0", "ARROYO_RACE_V1 1 1 0 0 1 0 9 0 3000 0 1000 0", "ARROYO_RACE_V1 1 1 0 1 1 0 9 1 3000 0 1000 0", "ARROYO_RACE_V1 1 3 0 1 1 9 9 0 0 0 1000 0", "ARROYO_RACE_V1 1 4 0 1 1 0 9 1 0 0 1000 0", "ARROYO_SCORES_V1 1 6", "ARROYO_SCORE_V1 1 0 1000 Browser_A -", "ARROYO_SCORE_V1 1 1 1000 Browser:A -", "ARROYO_SCORE_V1 1 1 1000 Browser_A - extra"}){bool threw=false;try{challengeNotice(bad);}catch(...){threw=true;}check(threw,"invalid phase identity and score bounds rejected");}
 {check(!challengeNotice("ARROYO_RACE_V2 7 2 0 1"),"unsupported version remains ordinary server text");auto event=json::parse(capture([]{challengeNotice("ARROYO_SCORES_V1 4 2");}));check(event["type"]=="challengeScoresClear"&&event["count"]==2,"score batch count decoded");event=json::parse(capture([]{challengeNotice("ARROYO_SCORE_V1 4 1 37129 Browser_A Browser_B");}));check(event["rank"]==1&&event["driverName"]=="Browser_A"&&event["passengerName"]=="Browser_B","score crew names decoded");event=json::parse(capture([]{challengeNotice("ARROYO_SCORE_V1 4 2 39000 Browser_C -");}));check(event["passengerName"]=="","solo result has no synthetic passenger");}
 {BitStream b;b.Write(uint16_t(2));str8(b,"ARROYO_RACE_V1 7 3 0 1 1 9 9 1000 0 1000 20000 0");RPCParameters p{};p.input=b.GetData();p.numberOfBitsOfData=b.GetNumberOfBitsUsed();auto event=json::parse(capture([&]{onRpc(&p,reinterpret_cast<void*>(101));}));check(event["type"]=="chat"&&event["id"]==2,"player chat cannot forge a server challenge award");}
 std::cout<<"PASS: directional codecs, malformed values, truncated reads, bounded reordered fragmentation\n";return 0;
 }catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<'\n';return 1;}}
